name: BountyHunter
version: 2.0
main: com.jared.bountyhunter.BountyHunter
api-version: 1.20
description: A GUI-based bounty hunting plugin with diamond, emerald, and netherite currency

commands:
  bounty:
    description: Place, list, or remove bounties on players
    usage: /bounty <gui|set|list|remove> [player] [currency] [amount]
    aliases: [bh, bounties]
